name: Run plugin tests

on:
  pull_request:
    branches: [main]
    paths:
      - src/**
      - test/**
      - package.json
      - package-lock.json
  workflow_dispatch:
    # manually triggered

# Required for test results reporting.
permissions:
  checks: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npm run code:lint
      - run: npm run test
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
          JIRA_SERVER_PASSWORD: ${{ secrets.JIRA_SERVER_PASSWORD }}
          JIRA_SERVER_USERNAME: ${{ secrets.JIRA_SERVER_USERNAME }}
          JIRA_SERVER_URL: ${{ secrets.JIRA_SERVER_URL }}
          JIRA_CLOUD_TOKEN: ${{ secrets.JIRA_CLOUD_TOKEN }}
          JIRA_CLOUD_EMAIL: ${{ secrets.JIRA_CLOUD_EMAIL }}
          JIRA_CLOUD_URL: ${{ secrets.JIRA_CLOUD_URL }}
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          files: |
            unit.xml
          time_unit: seconds
